
package com.training.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyRest", targetNamespace = "http://www.tttraining.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyRest {


    /**
     * 
     * @param person
     * @return
     *     returns com.training.ws.client.PersonType
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloTest", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.HelloTest")
    @ResponseWrapper(localName = "helloTestResponse", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.HelloTestResponse")
    public PersonType helloTest(
        @WebParam(name = "person", targetNamespace = "")
        PersonType person);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello5", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello5")
    @ResponseWrapper(localName = "hello5Response", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello5Response")
    public String hello5(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello4", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello4")
    @ResponseWrapper(localName = "hello4Response", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello4Response")
    public String hello4(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello3", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello3")
    @ResponseWrapper(localName = "hello3Response", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello3Response")
    public String hello3();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello2", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello2")
    @ResponseWrapper(localName = "hello2Response", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello2Response")
    public String hello2();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello7", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello7")
    @ResponseWrapper(localName = "hello7Response", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello7Response")
    public String hello7(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonType arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello6", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello6")
    @ResponseWrapper(localName = "hello6Response", targetNamespace = "http://www.tttraining.com", className = "com.training.ws.client.Hello6Response")
    public String hello6(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonType arg0);

}
